# Generated by Django 3.2.9 on 2021-12-08 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='makale başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
