# Generated by Django 3.2.9 on 2021-12-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_makale_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='makale',
            name='type',
            field=models.CharField(choices=[('SUC', 'Suç'), ('CEZA', 'Ceza'), ('SUCDEGİL', 'Suç Değil'), ('HUKUK', 'Hukuk')], default='SUC', max_length=20, verbose_name='makalenin tipi'),
        ),
    ]
