# Generated by Django 4.0.4 on 2022-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_makale_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='içerik')),
                ('title', models.CharField(default='Baslık', max_length=100, verbose_name='makale başlık')),
            ],
        ),
        migrations.AddField(
            model_name='makale',
            name='slug',
            field=models.SlugField(default=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makale',
            name='type',
            field=models.CharField(choices=[('Suç', 'Suç'), ('Ceza', 'Ceza'), ('Suç Değil', 'Suç Değil'), ('Hukuk', 'Hukuk')], default='Suç', max_length=20, verbose_name='makalenin tipi'),
        ),
    ]
