# Generated by Django 4.0.4 on 2022-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_slide_makale_slug_alter_makale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='slug',
            field=models.SlugField(),
        ),
    ]
