# Generated by Django 4.0.4 on 2022-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_makale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
