# Generated by Django 4.0.4 on 2022-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_makale_description_alter_makale_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='description',
            field=models.TextField(default='makale açıklama', max_length=300, verbose_name='makale açıklama'),
        ),
    ]
